Updated Go modules and imports to v2
karlsen-network/dnsseeder pull request #4
Opened 2024-09-24 16:42 UTC by Leon1777

* updated go modules to V2
* updated release workflow
* bumb version to v2.0.0

2024-09-24 18:55 UTC, lemois-1337 requested changes

2024-09-24 18:55 UTC, lemois-1337 commented on go.mod
>  module github.com/karlsen-network/dnsseeder
This has to become v2 as well `github.com/karlsen-network/dnsseeder/v2` and the relevant `*.go` and Docker files.

2024-09-24 19:35 UTC, Leon1777 commented on go.mod
>  module github.com/karlsen-network/dnsseeder
fixed in 2f9786b0f647ad7c71de1359ea67a9df75a0bf53

2025-05-09 23:31 UTC, okilisan approved these changes

2025-05-10 00:11 UTC, merged